--ALTER :객체를 수정하는 구문. 
--1. 컬럼 추가, 수정, 삭제
SELECT * FROM EMPLOYEE_COPY2;

ALTER TABLE EMPLOYEE_COPY2
ADD (EMP_NO VARCHAR2(20)); --데이터는 추가 안됨
ALTER TABLE EMPLOYEE_COPY2
ADD (LNAME VARCHAR2 (40) DEFAULT '한국'); --디폴트값 설정하기

INSERT INTO EMPLOYEE_COPY2 (EMP_ID, EMP_NAME, SALARY, DEPT_TITLE, JOB_NAME)
VALUES (903, '도대남', 5000000, '기술지원부', '과장');

DESC EMPLOYEE_COPY2;
/*EMP_ID     NOT NULL VARCHAR2(3)  
EMP_NAME   NOT NULL VARCHAR2(20) 
SALARY              NUMBER       
DEPT_TITLE          VARCHAR2(35) 
JOB_NAME            VARCHAR2(35) 
EMP_NO              VARCHAR2(2)  
LNAME               VARCHAR2(40)  */

--컬럼수정
ALTER TABLE EMPLOYEE_COPY2
MODIFY EMP_ID CHAR(3) --자료형만 바꾸기
MODIFY EMP_NAME VARCHAR2(30) --크기 바꾸기
MODIFY DEPT_TITLE CHAR(40) --자료형, 크기 바꾸기
MODIFY LNAME DEFAULT '미국'; --DEFAULT값 바꾸기

SELECT * FROM EMPLOYEE_COPY2; --위에서 이미 들어간 디폴트는 안 바뀜. 실행 후 넣는 디폴트가 수정된 것

ALTER TABLE EMPLOYEE_COPY2
MODIFY DEPT_TITLE VARCHAR2(40);

--컬럼 삭제
SELECT * FROM EMPLOYEE_COPY2;
ALTER TABLE EMPLOYEE_COPY2
DROP COLUMN EMP_NO;

ALTER TABLE EMPLOYEE_COPY2
DROP COLUMN LNAME;

ALTER TABLE EMPLOYEE_COPY2
DROP (SALARY, EMP_ID);

ROLLBACK;

ALTER TABLE USER_GRADE 
DROP COLUMN GRADE_CODE;


--제약조건 추가. 삭제
CREATE TABLE ALTER_GRADE(
    GRADE_CODE NUMBER,
    GRADE_NAME VARCHAR2(30)
    
    
);

ALTER TABLE ALTER_GRADE
ADD CONSTRAINT PK_AG_GC PRIMARY KEY (GRADE_CODE);

ALTER TABLE ALTER_GRADE
MODIFY GRADE_NAME CONSTRAINT NN_AG_GN NOT NULL;

CREATE TABLE ALTER_USER(
    USER_NO NUMBER, --PRIMARY KEY,
    USER_ID VARCHAR2(20), --UNIQUE,
    USER_PWD VARCHAR2(30),--NOT NULL,
    USER_NAME VARCHAR2(30), --NOT NULL,
    GENDER VARCHAR2(10), --CHECK
    PHONE VARCHAR2(30),
    EMAIL VARCHAR2(50),
    GRADE_CODE NUMBER --FOREIGN KEY
);

ALTER TABLE ALTER_USER
ADD PRIMARY KEY(USER_NO)
ADD UNIQUE (USER_ID)
MODIFY USER_PWD NOT NULL
MODIFY USER_NAME NOT NULL
ADD CHECK (GENDER IN ('남','여'))
ADD FOREIGN KEY(GRADE_CODE) REFERENCES ALTER_GRADE(GRADE_CODE);

--EX1.EMPLOYEE테이블의 DEPT_CODE에 외래키 제약조건 추가
--참조 테이블은 DEPARTMENT, 참조 컬럼은 DEPT_ID ( 기본키)
ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT(DEPT_ID);

--EX2. DEPARTMENT테이블의LOCATION_ID에 외래키 제약조건 추가
--참조 테이블은 LOCATION,참조 컬럼은LOCATION의 기본키
ALTER TABLE DEPARTMENT
ADD FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION; --컬럼안써도 자동으로 기본키랑 연결이 됨

--제약조건 삭제
SELECT UC.CONSTRAINT_NAME, UC.CONSTRAINT_TYPE, UC.TABLE_NAME,
    UCC.COLUMN_NAME, UC.SEARCH_CONDITION
FROM USER_CONSTRAINTS UC
JOIN USER_CONS_COLUMNS UCC ON(UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
WHERE UC.TABLE_NAME = 'ALTER_USER';

ALTER TABLE ALTER_USER
DROP CONSTRAINT SYS_C007375;

ALTER TABLE ALTER_USER
DROP CONSTRAINT SYS_C007371
MODIFY USER_PWD NULL;       --DROP다음에 MODIFY 나올 것(순서유의)  MODIFY(USER_PWD, , ,)

--테이블명, 컬럼, 제약조건 이름 변경
SELECT * FROM CONS_NAME;
ALTER TABLE CONS_NAME
RENAME COLUMN TEST_DATA1 TO TEST1;

ALTER TABLE CONS_NAME
RENAME COLUMN TEST_DATA2 TO TEST2;

SELECT UC.CONSTRAINT_NAME, UC.CONSTRAINT_TYPE, UC.TABLE_NAME,
    UCC.COLUMN_NAME, UC.SEARCH_CONDITION
FROM USER_CONSTRAINTS UC
JOIN USER_CONS_COLUMNS UCC ON(UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
WHERE UC.TABLE_NAME = 'USER_FOREIGNKEY2';

ALTER TABLE USER_FOREIGNKEY2
RENAME CONSTRAINT SYS_C007333 TO NN_UF2_PWE;

ALTER TABLE USER_FOREIGNKEY2
RENAME CONSTRAINT SYS_C007334 TO PK_UF2_NO2;

ALTER TABLE USER_FOREIGNKEY2
RENAME CONSTRAINT SYS_C007335 TO PK_UF2_ID;

ALTER TABLE MEMBER RENAME TO MEN;

--DROP (삭제됨)
DROP TABLE MEN --제약조건은 남아있고 테이블만 사라짐
CASCADE CONSTRAINTS; --제약조건도 삭제